---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ggplot2)
```

```{r}
x <- c(151, 174, 138, 186, 128, 136, 179, 163, 152, 131)
y <- c(63, 81, 56, 91, 47, 57, 76, 72, 62, 48)

print(x)
print(y)
```

```{r}
data <- data.frame(x, y)
print(data)
```

```{r}
ggplot(data, aes(x=x, y=y)) + geom_point()
```

```{r}
regression_ <- lm(y~x)
print(regression_)
print(summary(regression_))
```

```{r}
# ggplot(data, aes(x=x, y=y)) + geom_line()
#plot(y,x,col = "blue",main = "Height & Weight Regression", abline(lm(x~y)),cex = 1.3,pch = 16,xlab = "Weight in Kg",ylab ="Height in cm")
```


```{r}
ggplot(data, aes(x=x, y=y)) + geom_point() + geom_smooth(method="lm")
```


```{r}
pca_df <- read.table(url("https://archive.ics.uci.edu/ml/machine-learning-databases/00291/airfoil_self_noise.dat"), header=FALSE, skip=3)

print(pca_df)

plot(pca_df)
```
```{r}
# pca <- prcomp(pca_df, scale. = T)
y <- pca_df$V6
print(head(y))
plot(y)
```
```{r}
tracemem(y)==tracemem(pca_df$V6)
```


```{r}
print(pca)
```


```{r}

```
